export const actionTypes = {
    FETCHING_REQUEST: "FETCHING_REQUEST",
    FETCH_DRINKS_SUCCESS: "FETCH_DRINKS_SUCCESS",
    SET_FILTER: "SET_FILTER",
    CLEAR_FILTER: "CLEAR_FILTER",
    RAISE_ERROR: "RAISE_ERROR",
};